### ISSUE TITLE
不兼容journeymap

### ISSUE THREAD

**Issue by huangsijun17** [PFCraft/PFWorld#2]
使用本插件tp入世界后，journeymap依然认为是在主世界，导致journeymap的地图和引导点异常。

**Comment by huangsijun17** [comment]
1.12.2 akarin端

**Comment by huangsijun17** [comment]
刚刚看到，Jmap的官网有插件：

https://minecraft.curseforge.com/projects/journeymap-server/files

**Comment by Mgazul** [comment]
> 使用本插件TP入世界后，journeymap依然认为是在主世界，导致journeymap的地图和引导点异常。

异常后有什么提示吗

**Comment by huangsijun17** [comment]
> > 使用本插件TP入世界后，journeymap依然认为是在主世界，导致journeymap的地图和引导点异常。
> 
> 异常后有什么提示吗

只是Jmap将PF定义的世界认成了主世界，从而导致多个世界的地图重叠了，包括地图和引导标识等等。没有任何错误信息。
搜了一大圈，发现Jmap有一个自己的插件，来兼容第三方的多世界插件的。安装后Jmap就识别出是插件定义的世界，而非主世界了。
